"""empty message

Revision ID: 706b48abd5bb
Revises: 69b9e725a5d7
Create Date: 2018-11-26 13:56:07.775616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706b48abd5bb'
down_revision = '69b9e725a5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
